version: '3.4'

services:
  admin:
    #image: ${DOCKER_REGISTRY-}gasinfoadmin
    #volumes:
      #- gas_info_admin:/app
    build:
      context: .
      dockerfile: GasInfoAdmin/Dockerfile
    depends_on:
      - sqldb
    ports:
      - "49153:5003"
  api:
    #image: ${DOCKER_REGISTRY-}gasinfoapi
    #volumes:
      #- gas_info_api:/app
    build:
      context: .
      dockerfile: GasInfoApi/Dockerfile
    depends_on:
      - sqldb
    ports:
      #- "49152:5002"
      - "1080:80"
    environment:
      - ASPNETCORE_URLS=http://+:5002;http://+:80
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes: 
      - dbdata:/var/opt/mssql/data
    container_name: sql_gas_info
    environment:
      - SA_PASSWORD=MyPass@word
      - ACCEPT_EULA=Y
      - MYSQL_PID=Express
    ports:
      - "1440:1433"   
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'd/mount/sql'
  gas_info_admin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'd/mount/gas_info_admin'
  gas_info_api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'd/mount/gas_info_api'
