// <auto-generated />
using System;
using DA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DA.Migrations
{
    [DbContext(typeof(GasInfoDbContext))]
    partial class GasInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DA.Entities.AmmountCb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cb1")
                        .HasColumnType("int");

                    b.Property<int>("Cb2")
                        .HasColumnType("int");

                    b.Property<int>("Cb3")
                        .HasColumnType("int");

                    b.Property<int>("Cb4")
                        .HasColumnType("int");

                    b.Property<int>("Cb5")
                        .HasColumnType("int");

                    b.Property<int>("Cb6")
                        .HasColumnType("int");

                    b.Property<int>("Cb7")
                        .HasColumnType("int");

                    b.Property<int>("Cb8")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<int>("OutputMultipliersId")
                        .HasColumnType("int");

                    b.Property<int>("PKP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.HasIndex("OutputMultipliersId");

                    b.ToTable("AmmountCb");
                });

            modelBuilder.Entity("DA.Entities.Asdue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<decimal>("Gps2Gss1")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<decimal>("Gps2Gss2")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<decimal>("NaturalGasQn")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal>("OutPkg")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<decimal>("TecNorth")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.Property<decimal>("TecSouth")
                        .HasPrecision(16, 6)
                        .HasColumnType("numeric(16,6)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Asdue");
                });

            modelBuilder.Entity("DA.Entities.CharacteristicsDgAll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("CharacteristicsDg");
                });

            modelBuilder.Entity("DA.Entities.CharacteristicsKgAll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("CharacteristicsKg");
                });

            modelBuilder.Entity("DA.Entities.DevicesKip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DevicesKip");
                });

            modelBuilder.Entity("DA.Entities.DgPgChmkEb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsDgCb1")
                        .HasColumnType("int");

                    b.Property<int>("ConsDgCb2")
                        .HasColumnType("int");

                    b.Property<int>("ConsDgCb3")
                        .HasColumnType("int");

                    b.Property<int>("ConsDgCb4")
                        .HasColumnType("int");

                    b.Property<int>("ConsPgGru1")
                        .HasColumnType("int");

                    b.Property<int>("ConsPgGru2")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DgPgChmkEb");
                });

            modelBuilder.Entity("DA.Entities.KgChmkEb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Consumption")
                        .HasPrecision(17, 10)
                        .HasColumnType("numeric(17,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("KgChmkEb");
                });

            modelBuilder.Entity("DA.Entities.OutputMultipliers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cb1")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb2")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb3")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb4")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb5")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb6")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb7")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Cb8")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<decimal>("Fv")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("PKP")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Peka")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.Property<decimal>("Sv")
                        .HasPrecision(14, 10)
                        .HasColumnType("numeric(14,10)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("OutputMultipliers");
                });

            modelBuilder.Entity("DA.Entities.Pressure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<decimal>("Value")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Pressure");
                });

            modelBuilder.Entity("DA.Entities.QualityAll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Quality");
                });

            modelBuilder.Entity("DA.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DA.Entities.Tec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Chmk")
                        .HasPrecision(16, 10)
                        .HasColumnType("numeric(16,10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<decimal>("TecNorth")
                        .HasPrecision(16, 10)
                        .HasColumnType("numeric(16,10)");

                    b.Property<decimal>("TecSouth")
                        .HasPrecision(16, 10)
                        .HasColumnType("numeric(16,10)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Tec");
                });

            modelBuilder.Entity("DA.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "AsupAdmin",
                            Password = "55914",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("DA.Entities.AmmountCb", b =>
                {
                    b.HasOne("DA.Entities.OutputMultipliers", "OutputMultipliers")
                        .WithMany("AmmountCbs")
                        .HasForeignKey("OutputMultipliersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutputMultipliers");
                });

            modelBuilder.Entity("DA.Entities.CharacteristicsDgAll", b =>
                {
                    b.OwnsOne("DA.Entities.Characteristics.DG", "Kc1", b1 =>
                        {
                            b1.Property<int>("CharacteristicsDgAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("CO")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("H2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("N2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("CharacteristicsDgAllId");

                            b1.ToTable("CharacteristicsDg");

                            b1.WithOwner()
                                .HasForeignKey("CharacteristicsDgAllId");
                        });

                    b.OwnsOne("DA.Entities.Characteristics.DG", "Kc2", b1 =>
                        {
                            b1.Property<int>("CharacteristicsDgAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("CO")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("H2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("N2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("CharacteristicsDgAllId");

                            b1.ToTable("CharacteristicsDg");

                            b1.WithOwner()
                                .HasForeignKey("CharacteristicsDgAllId");
                        });

                    b.Navigation("Kc1");

                    b.Navigation("Kc2");
                });

            modelBuilder.Entity("DA.Entities.CharacteristicsKgAll", b =>
                {
                    b.OwnsOne("DA.Entities.Characteristics.KG", "Kc1", b1 =>
                        {
                            b1.Property<int>("CharacteristicsKgAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("CH4")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CnHm")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("H2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("N2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("O2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("CharacteristicsKgAllId");

                            b1.ToTable("CharacteristicsKg");

                            b1.WithOwner()
                                .HasForeignKey("CharacteristicsKgAllId");
                        });

                    b.OwnsOne("DA.Entities.Characteristics.KG", "Kc2", b1 =>
                        {
                            b1.Property<int>("CharacteristicsKgAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("CH4")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CO2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("CnHm")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("H2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("N2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("O2")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("CharacteristicsKgAllId");

                            b1.ToTable("CharacteristicsKg");

                            b1.WithOwner()
                                .HasForeignKey("CharacteristicsKgAllId");
                        });

                    b.Navigation("Kc1");

                    b.Navigation("Kc2");
                });

            modelBuilder.Entity("DA.Entities.DevicesKip", b =>
                {
                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cb1", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cb2", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cb3", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cb4", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cu1", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Cu2", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Grp4", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Gru1", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Gru2", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Gsuf45", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Spo", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceDefault", "Uvtp", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceMsKs", "Pkc", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");

                            b1.OwnsOne("DA.Entities.Devices.ConsumptionMsKs", "Consumption", b2 =>
                                {
                                    b2.Property<int>("DeviceMsKsDevicesKipId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("Ks")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.Property<decimal>("Ms")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.HasKey("DeviceMsKsDevicesKipId");

                                    b2.ToTable("DevicesKip");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceMsKsDevicesKipId");
                                });

                            b1.Navigation("Consumption");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceTBHDefault", "Cb5", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("TempBeforeHeating")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceTBHDefault", "Cb6", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Consumption")
                                .HasColumnType("int");

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("TempBeforeHeating")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceTBHMsKs", "Cb7", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("TempBeforeHeating")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");

                            b1.OwnsOne("DA.Entities.Devices.ConsumptionMsKs", "Consumption", b2 =>
                                {
                                    b2.Property<int>("DeviceTBHMsKsDevicesKipId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("Ks")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.Property<decimal>("Ms")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.HasKey("DeviceTBHMsKsDevicesKipId");

                                    b2.ToTable("DevicesKip");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceTBHMsKsDevicesKipId");
                                });

                            b1.Navigation("Consumption");
                        });

                    b.OwnsOne("DA.Entities.Devices.DeviceTBHMsKs", "Cb8", b1 =>
                        {
                            b1.Property<int>("DevicesKipId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Pressure")
                                .HasColumnType("int");

                            b1.Property<decimal>("TempBeforeHeating")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)");

                            b1.HasKey("DevicesKipId");

                            b1.ToTable("DevicesKip");

                            b1.WithOwner()
                                .HasForeignKey("DevicesKipId");

                            b1.OwnsOne("DA.Entities.Devices.ConsumptionMsKs", "Consumption", b2 =>
                                {
                                    b2.Property<int>("DeviceTBHMsKsDevicesKipId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<decimal>("Ks")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.Property<decimal>("Ms")
                                        .HasPrecision(16, 6)
                                        .HasColumnType("numeric(16,6)");

                                    b2.HasKey("DeviceTBHMsKsDevicesKipId");

                                    b2.ToTable("DevicesKip");

                                    b2.WithOwner()
                                        .HasForeignKey("DeviceTBHMsKsDevicesKipId");
                                });

                            b1.Navigation("Consumption");
                        });

                    b.Navigation("Cb1");

                    b.Navigation("Cb2");

                    b.Navigation("Cb3");

                    b.Navigation("Cb4");

                    b.Navigation("Cb5");

                    b.Navigation("Cb6");

                    b.Navigation("Cb7");

                    b.Navigation("Cb8");

                    b.Navigation("Cu1");

                    b.Navigation("Cu2");

                    b.Navigation("Grp4");

                    b.Navigation("Gru1");

                    b.Navigation("Gru2");

                    b.Navigation("Gsuf45");

                    b.Navigation("Pkc");

                    b.Navigation("Spo");

                    b.Navigation("Uvtp");
                });

            modelBuilder.Entity("DA.Entities.QualityAll", b =>
                {
                    b.OwnsOne("DA.Entities.Quality", "Kc1", b1 =>
                        {
                            b1.Property<int>("QualityAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("A")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("V")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("W")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("QualityAllId");

                            b1.ToTable("Quality");

                            b1.WithOwner()
                                .HasForeignKey("QualityAllId");
                        });

                    b.OwnsOne("DA.Entities.Quality", "Kc2", b1 =>
                        {
                            b1.Property<int>("QualityAllId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<decimal>("A")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("V")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.Property<decimal>("W")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)");

                            b1.HasKey("QualityAllId");

                            b1.ToTable("Quality");

                            b1.WithOwner()
                                .HasForeignKey("QualityAllId");
                        });

                    b.Navigation("Kc1");

                    b.Navigation("Kc2");
                });

            modelBuilder.Entity("DA.Entities.User", b =>
                {
                    b.HasOne("DA.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DA.Entities.OutputMultipliers", b =>
                {
                    b.Navigation("AmmountCbs");
                });

            modelBuilder.Entity("DA.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
